apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      name: web
  selector:
    app: {{ include "web.name" . }}