name: CD

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push the Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/web:$GITHUB_REF_NAME && docker push ${{ secrets.DOCKER_USERNAME }}/web:$GITHUB_REF_NAME
   
    - uses: actions/checkout@v4
      with:          
        repository: 'ngo-bang/config-web'
        token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    - name: update config repo
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        sed -i 's/tag: ".*/tag: "${{  github.ref_name }}"/' values.yaml
        git add .
        git commit -m "update"
        git push origin main
